apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ping
  namespace: ping-ns
spec:
  selector:
    matchLabels:
      app: redis-ping
  replicas: 1
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: redis-ping
    spec:
      containers:
      - name: redis-ping
        image: redis
        ports:
        - containerPort: 6379
