apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: ping-ns
  labels:
    app: redis-ping
spec:
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
  selector:
    app: redis-ping
